### ISSUE TITLE
All of those realtek drivers, including the manufacturer ones, leak the passwords in cleartext to /tmp. Can we fix that?

### ISSUE THREAD

**Issue by hipunk** [chris1111/Wireless-USB-Adapter#135]
Hi,

thanks for the good work you have done. This driver is more stable than the one I got delivered from the USB-Stick ("comfast cf-924ac v2") manufacturer via DVD. The menulet also doesn't launch under root anymore, which I like. Two very good improvements!

However, this thing still leaks the passwords in cleartext into /tmp, which is unacceptable in certain circumstances.
You almost always never want something like this to happen.

I would welcome it, if we could at least hide into a directory that the regular user accounts cannot access. Right now, we can steal the passwords with a simple bash oneliner you just have to trick users into executing. It's so simple, it's spooky.

Greetz

**Comment by chris1111** [comment]
There is nothing scary about that, a router password is not a user account password.
If you are not happy with this fact you can complain to your USB Wifi supplier in this case Comfast but I don't think they can do anything because it is a Realtek App and they have no source to change or modify it but I don't worry about it at all because everything in /tmp is deleted after each reboot
