### ISSUE TITLE
V11 would not install

### ISSUE THREAD

**Issue by Gewurztraminer** [chris1111/Wireless-USB-Adapter#56]
Mac Pro with 10.15 Cat, but need some apps on 10.13 HS.
V10 ran fine when I installed Catalina.
New HD with HS, ran V11 pkg which failed early in installation progress bar.
Went back to V10, installed and working.
Thanks Chris, useful drivers.

**Comment by chris1111** [comment]
It is strange because it has already been tested and I retest here for you 😀
Allor see you that the problem probably comes from your High Sierra
Make sure before retesting that you have no program file in User / HOME / Shared then uninstall it and try with the SIP deactivate because for my test the SIP was deactivated

## See video High Sierra with V11 ⬇︎
[![Modular Image Creation](https://user-images.githubusercontent.com/6248794/76169102-84ff8080-614b-11ea-905f-4d10f7081262.png)](https://youtu.be/kARYXXXdlx0)
